version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/build"
    schedule:
      interval: weekly
